---
- name: Authenticate to RHVM API
  ansible.builtin.include_tasks: ovirt_auth.yml

- name: Log AAP survey inputs
  ansible.builtin.debug:
    msg: "Adding {{ increase_size_mb }}MB of memory to VM {{ target_vm }}"

- name: Collect VM info from RHVM
  redhat.rhv.ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: name="{{ target_vm }}"
  register: ovirt_vm_info_reg

- name: Dump VM info
  ansible.builtin.debug:
    var: ovirt_vm_info_reg
  when: debug_mode | bool

- ansible.builtin.fail:
    msg: "VM {{ target_vm }} not found at {{ rhvm_url }}"
  when: ovirt_vm_info_reg.ovirt_vms == []

# Memory is returned in bytes
- name: Set fact for VM memory allocation
  ansible.builtin.set_fact:
    vm_memory: "{{ ovirt_vm_info_reg.ovirt_vms[0].memory }}"

- ansible.builtin.set_fact:
    vm_state: "{{ ovirt_vm_info_reg.ovirt_vms[0].status }}"

- name: Set fact for new total memory allocation
  ansible.builtin.set_fact:
    new_total_memory: "{{ ( increase_size_mb | int ) + ( vm_memory | int / 1024 / 1024 ) }}"

- ansible.builtin.debug:
    msg: "New total memory allocation will be {{ new_total_memory | int }}MB"

- name: Stop VM if running
  ansible.builtin.include_tasks: stop_vm.yml
  when: vm_state is match("up")

# Need to reset the power status flag as the above task is skipped if the VM is already down
- name: Reset power status flag
  redhat.rhv.ovirt_vm_info:
    auth: "{{ ovirt_auth }}"
    pattern: name="{{ target_vm }}"
    all_content: true
  register: vm_power_state_reg

- name: Allocate memory to VM
  redhat.rhv.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    name: "{{ target_vm }}"
    memory: "{{ new_total_memory | int }}MiB"
    memory_guaranteed: "{{ new_total_memory | int }}MiB"
  register: ovirt_vm_reg

- ansible.builtin.debug:
    var: ovirt_vm_reg
  when: debug_mode | bool

- name: Restart VM
  ansible.builtin.include_tasks: start_vm.yml
  when: vm_power_state_reg.ovirt_vms[0].status is match("down")

- name: Verify memory allocation
  block:
    - redhat.rhv.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name="{{ target_vm }}"
      register: ovirt_vm_memory_check_reg
    - ansible.builtin.debug:
        msg: "Memory allocation to {{ target_vm }} now {{ ovirt_vm_memory_check_reg.ovirt_vms[0].memory | int / 1024 /1024 }}MB"

- name: Revoke authentication token
  ansible.builtin.include_tasks: revoke_ovirt_auth.yml
