---
- name: Stop VM
  block:
    - ansible.builtin.debug:
        msg: "Stopping VM..."
    - redhat.rhv.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        name: "{{ target_vm }}"
        state: stopped
    - ansible.builtin.debug:
        msg: "Waiting for server to complete shutdown..."
    - redhat.rhv.ovirt_vm_info:
        auth: "{{ ovirt_auth }}"
        pattern: name="{{ target_vm }}"
        all_content: true
      register: is_stopped_reg
      until: is_stopped_reg.ovirt_vms[0].status is match("down")
      retries: 10
      delay: 30
    - ansible.builtin.debug:
        msg: "VM {{ target_vm }} is {{ is_stopped_reg.ovirt_vms[0].status }}
